### ISSUE TITLE
precision is undefined due to block scope

### ISSUE THREAD

**Issue by nicolaszimmer** [upphiminn/jDBSCAN#7]
Thanks a lot for your excellent work! Just one thing with haversine_distance():
		
```
if (typeof precision === 'undefined') {
 let precision = 4;
}
```

should either be

```
if (typeof precision === 'undefined') {
 var precision = 4;
}
```

to avoid the block scope problem with let or you could get rid of the if-statement completely as you don't have any setters for this defined (so its always undefined).

**Comment by upphiminn** [comment]
Good catch, will fix it, thanks!
